language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
bundler_args: ""
script: "bundle exec rake spec"
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails4.1.gemfile
